
import { Instance, InstanceStatus, Tier, AnalyticsData, Appointment, ChatMessage, ChatRoom, Tenant, User, UserRole, McpProvider } from './types';

export const MOCK_INSTANCES: Instance[] = [
  {
    id: 'inst-001',
    name: 'Customer-Support-Bot-A',
    tier: Tier.PRO,
    status: InstanceStatus.ONLINE,
    region: 'us-east-1',
    version: 'v2.4.1',
    uptime: '14d 2h',
    created: '2023-10-15',
    health: 98,
    lastSeen: '2 mins ago',
    licenseExpiry: '2025-10-15',
  },
  {
    id: 'inst-002',
    name: 'Internal-HR-Assistant',
    tier: Tier.STARTER,
    status: InstanceStatus.BOOTSTRAPPING,
    region: 'eu-central-1',
    version: 'v2.5.0-beta',
    uptime: '0m',
    created: '2023-11-01',
    health: 45,
    lastSeen: 'Just now',
    licenseExpiry: '2024-11-01',
  },
  {
    id: 'inst-003',
    name: 'Sales-Analysis-RAG',
    tier: Tier.ENTERPRISE,
    status: InstanceStatus.PENDING_APPROVAL,
    region: 'us-west-2',
    version: 'v2.3.9',
    uptime: '-',
    created: '2023-11-02',
    health: 0,
    lastSeen: 'Never',
    licenseExpiry: '2024-12-31',
  },
  {
    id: 'inst-004',
    name: 'Legacy-Chat-V1',
    tier: Tier.STARTER,
    status: InstanceStatus.OFFLINE,
    region: 'ap-southeast-1',
    version: 'v1.8.0',
    uptime: '-',
    created: '2023-01-10',
    health: 0,
    lastSeen: '5 days ago',
    licenseExpiry: '2023-12-01',
  },
  {
    id: 'inst-005',
    name: 'FinTech-Secure-Core',
    tier: Tier.ENTERPRISE,
    status: InstanceStatus.ONLINE,
    region: 'us-east-1',
    version: 'v2.4.1',
    uptime: '45d 12h',
    created: '2023-06-20',
    health: 99,
    lastSeen: '1 min ago',
    licenseExpiry: '2026-06-20',
  },
  {
    id: 'inst-006',
    name: 'DevOps-Assistant',
    tier: Tier.PRO,
    status: InstanceStatus.ONLINE,
    region: 'us-west-1',
    version: 'v2.4.1',
    uptime: '2d 4h',
    created: '2023-09-10',
    health: 92,
    lastSeen: '5 mins ago',
    licenseExpiry: '2024-09-10',
  },
  {
    id: 'inst-007',
    name: 'Legal-Doc-Reviewer',
    tier: Tier.ENTERPRISE,
    status: InstanceStatus.PENDING_APPROVAL,
    region: 'eu-west-2',
    version: 'v2.5.0',
    uptime: '-',
    created: '2023-11-20',
    health: 0,
    lastSeen: 'Never',
    licenseExpiry: '2025-01-01',
  },
  {
    id: 'inst-008',
    name: 'Marketing-Copy-Bot',
    tier: Tier.STARTER,
    status: InstanceStatus.ACTIVE,
    region: 'us-east-1',
    version: 'v2.3.5',
    uptime: '10d 1h',
    created: '2023-08-05',
    health: 88,
    lastSeen: '1 hour ago',
    licenseExpiry: '2024-08-05',
  },
  {
    id: 'inst-009',
    name: 'Data-Entry-Automator',
    tier: Tier.PRO,
    status: InstanceStatus.ERROR,
    region: 'ap-northeast-1',
    version: 'v2.2.0',
    uptime: '0m',
    created: '2023-07-15',
    health: 12,
    lastSeen: '2 days ago',
    licenseExpiry: '2024-07-15',
  },
  {
    id: 'inst-010',
    name: 'Executive-Briefing-AI',
    tier: Tier.ENTERPRISE,
    status: InstanceStatus.OFFLINE,
    region: 'us-east-2',
    version: 'v2.4.0',
    uptime: '-',
    created: '2023-10-01',
    health: 0,
    lastSeen: '1 week ago',
    licenseExpiry: '2024-10-01',
  },
  {
    id: 'inst-011',
    name: 'Onboarding-Guide-V2',
    tier: Tier.STARTER,
    status: InstanceStatus.ONLINE,
    region: 'eu-central-1',
    version: 'v2.4.2',
    uptime: '5h 30m',
    created: '2023-11-25',
    health: 100,
    lastSeen: 'Just now',
    licenseExpiry: '2024-11-25',
  },
  {
    id: 'inst-012',
    name: 'Translation-Service-Beta',
    tier: Tier.PRO,
    status: InstanceStatus.BOOTSTRAPPING,
    region: 'sa-east-1',
    version: 'v2.6.0-alpha',
    uptime: '-',
    created: '2023-11-26',
    health: 50,
    lastSeen: 'Just now',
    licenseExpiry: '2024-05-26',
  },
  {
    id: 'inst-013',
    name: 'Inventory-Manager-AI',
    tier: Tier.PRO,
    status: InstanceStatus.ONLINE,
    region: 'us-west-2',
    version: 'v2.3.8',
    uptime: '30d 12h',
    created: '2023-05-10',
    health: 95,
    lastSeen: '10 mins ago',
    licenseExpiry: '2024-05-10',
  }
];

export const ANALYTICS_DATA: AnalyticsData[] = [
  { name: 'Mon', queries: 4000, latency: 240, cost: 240 },
  { name: 'Tue', queries: 3000, latency: 139, cost: 221 },
  { name: 'Wed', queries: 2000, latency: 980, cost: 229 },
  { name: 'Thu', queries: 2780, latency: 390, cost: 200 },
  { name: 'Fri', queries: 1890, latency: 480, cost: 218 },
  { name: 'Sat', queries: 2390, latency: 380, cost: 250 },
  { name: 'Sun', queries: 3490, latency: 430, cost: 210 },
];

export const PRODUCTS = [
  { name: 'Sidekick', description: 'AI Companion for Ops', status: 'Live', version: '2.4.0' },
  { name: 'Guardian', description: 'Security & Compliance', status: 'Beta', version: '0.9.1' },
  { name: 'Analyst', description: 'Deep Data Insights', status: 'Coming Soon', version: '-' },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  { id: 'apt-1', customerName: 'Sarah Connor', date: '2023-11-10', time: '14:00', status: 'Confirmed', assignedBot: 'Sales-Bot-01' },
  { id: 'apt-2', customerName: 'John Doe', date: '2023-11-12', time: '09:30', status: 'Pending', assignedBot: 'Support-Alpha' },
  { id: 'apt-3', customerName: 'Emily Clark', date: '2023-11-12', time: '11:00', status: 'Cancelled', assignedBot: 'Sales-Bot-01' },
];

export const MOCK_CHAT_ROOMS: ChatRoom[] = [
  { id: 'room-1', user: 'Visitor #9942', lastMessage: 'I need help with pricing.', time: '2m ago', unread: 1 },
  { id: 'room-2', user: 'Visitor #8821', lastMessage: 'Thanks, that works.', time: '1h ago', unread: 0 },
  { id: 'room-3', user: 'Enterprise Lead', lastMessage: 'Can I schedule a demo?', time: '3h ago', unread: 0 },
];

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Alex Sterling', email: 'alex@pairmind.ai', role: UserRole.SUPER_ADMIN, avatar: 'https://picsum.photos/100/100' },
  { id: 'u2', name: 'Jamie Chen', email: 'jamie@pairmind.ai', role: UserRole.TENANT_ADMIN, avatar: 'https://picsum.photos/101/101' },
  { id: 'u3', name: 'Sam Wilson', email: 'sam@company.com', role: UserRole.USER, avatar: 'https://picsum.photos/102/102' },
];

export const MOCK_TENANTS: Tenant[] = [
  { id: 't1', name: 'Acme Corp', plan: 'Enterprise', users: 12, status: 'Active' },
  { id: 't2', name: 'StartUp Inc', plan: 'Starter', users: 3, status: 'Active' },
  { id: 't3', name: 'Global Logistics', plan: 'Pro', users: 45, status: 'Suspended' },
  { id: 't-1765619682133', name: 'hari', plan: '', users: 1, status: 'Active' },
];

export const MOCK_MCP_PROVIDERS: McpProvider[] = [
  { 
    id: 'mcp-1', 
    name: 'PostgreSQL Connector', 
    description: 'Read/Write access to SQL databases via natural language.', 
    category: 'Database', 
    status: 'Installed', 
    icon: 'database',
    version: '2.1.0',
    installedVersion: '2.1.0',
    isConfigured: true
  },
  { 
    id: 'mcp-2', 
    name: 'Google Search Grounding', 
    description: 'Enable real-time web search capabilities for your agents.', 
    category: 'Search', 
    status: 'Available', 
    icon: 'search',
    version: '1.5.2'
  },
  { 
    id: 'mcp-3', 
    name: 'Slack Ops', 
    description: 'Manage channels and send notifications from AI workflows.', 
    category: 'Productivity', 
    status: 'Update Available', 
    icon: 'message-square',
    version: '3.0.1',
    installedVersion: '2.9.8',
    isConfigured: true
  },
  { 
    id: 'mcp-4', 
    name: 'Stripe Payments', 
    description: 'Process refunds and check subscription status.', 
    category: 'Payment', 
    status: 'Available', 
    icon: 'credit-card',
    version: '1.2.0'
  },
  { 
    id: 'mcp-5', 
    name: 'Jira Integration', 
    description: 'Create and update tickets directly from conversation contexts.', 
    category: 'Productivity', 
    status: 'Available', 
    icon: 'trello',
    version: '2.0.0'
  },
];
